openapi: 3.0.0
info:
  title: to-do-API
  version: 1.0.0
  description: API para la gestión de tareas
  contact:
    name: Alejo Filartiga
servers:
  - url: https://to-do-api-kappa-ruby.vercel.app
    description: Servidor de producción
  - url: http://localhost:8080
    description: Servidor local de desarrollo
paths:
  /:
    get:
      summary: Obtener todas las tareas
      tags:
        - Tasks
      responses:
        200:
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Crear una nueva tarea
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: Tarea creada correctamente
  /{id}:
    delete:
      summary: Eliminar una tarea
      tags:
        - Tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de la tarea a eliminar
      responses:
        200:
          description: Tarea eliminada correctamente
        400:
          description: La tarea no existe
    patch:
      summary: Actualizar una tarea
      tags:
        - Tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de la tarea a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: Estado de la tarea
      responses:
        200:
          description: Tarea actualizada correctamente
components:
  schemas:
    Task:
      type: object
      required:
        - title
      properties:
        _id:
          type: string
          description: ID autogenerado de la tarea
        title:
          type: string
          description: Nombre de la tarea
        completed:
          type: boolean
          description: Estado de la tarea
      example:
        _id: 1
        title: Practicar guitarra
        completed: false
